from enum import Enum

class AgentErrorCode(str, Enum):
    STATE_VALIDATON_ERROR = "STATE_VALIDATION_ERROR"
    LLM_INVOCATION_ERROR = "LLM_INVOCATION_ERROR"
    JSON_PARSING_ERROR = "JSON_PARSING_ERROR"